version: '{build}'
image: Visual Studio 2022
configuration: Release

environment:
  nodejs_version: '20'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - npm run build
  - ps: if (Test-Path dist) { Get-ChildItem dist } else { Write-Error "Папка dist не найдена!" }

test_script:
  - npm test

deploy_script:
  - ps: npm run deploy

on_success:
  - ps: echo "Deployment to GitHub Pages successful!"



